from __future__ import annotations

from .parse import Door


def _esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_python(door: Door) -> str:
    checks = []
    for c in door.checks:
        if c.kind == "exists":
            checks.append(f'    assert (ROOT / "{_esc(c.args[0])}").exists()')
        elif c.kind == "words":
            src = "INTENT" if c.args[0] == "intent" else "PATTERN"
            checks.append(f"    assert len({src}.split()) <= {c.args[1]}")
        elif c.kind == "run":
            checks.append(f"    assert subprocess.run({c.args[0]!r}, shell=True, cwd=ROOT).returncode == 0")
        elif c.kind == "contains":
            checks.append(f'    assert {c.args[1]!r} in (ROOT / "{_esc(c.args[0])}").read_text()')
        elif c.kind == "eq":
            checks.append(f'    assert (ROOT / "{_esc(c.args[0])}").read_text() == {c.args[1]!r}')
    body = "\n".join(checks) or "    pass"
    return (
        "# generated by ya-ra rv1\n"
        "from pathlib import Path\nimport subprocess\n"
        "ROOT = Path.cwd()\n"
        f'INTENT = "{_esc(door.intent)}"\n'
        f'PATTERN = "{_esc(door.pattern)}"\n'
        f'SIGNED = "{_esc(door.signer)} / {_esc(door.timestamp)}"\n'
        "def test_door():\n"
        "    assert len(INTENT.split()) <= 17\n"
        "    assert len(PATTERN.split()) <= 17\n"
        f"{body}\n"
        'if __name__ == "__main__":\n'
        "    test_door()\n"
        '    print("ok")\n'
    )


def emit_rust(door: Door) -> str:
    stmts = [
        "    assert!(intent.split_whitespace().count() <= 17);",
        "    assert!(pattern.split_whitespace().count() <= 17);",
    ]
    for c in door.checks:
        if c.kind == "exists":
            stmts.append(f'    assert!(std::path::Path::new("{_esc(c.args[0])}").exists());')
        elif c.kind == "words":
            var = "intent" if c.args[0] == "intent" else "pattern"
            stmts.append(f"    assert!({var}.split_whitespace().count() <= {c.args[1]});")
        elif c.kind == "run":
            stmts.append(
                f'    assert!(std::process::Command::new("sh").arg("-c").arg("{_esc(c.args[0])}")'
                ".status().unwrap().success());"
            )
        elif c.kind == "contains":
            stmts.append(
                f'    assert!(std::fs::read_to_string("{_esc(c.args[0])}").unwrap().contains("{_esc(c.args[1])}"));'
            )
        elif c.kind == "eq":
            stmts.append(
                f'    assert_eq!(std::fs::read_to_string("{_esc(c.args[0])}").unwrap(), "{_esc(c.args[1])}");'
            )
    return (
        "// generated by ya-ra rv1\nfn main() {\n"
        f'    let intent = "{_esc(door.intent)}";\n'
        f'    let pattern = "{_esc(door.pattern)}";\n'
        + "\n".join(stmts)
        + '\n    println!("ok");\n}\n'
    )


def emit_c(door: Door) -> str:
    lines = [
        "/* generated by ya-ra rv1 */",
        "#include <stdio.h>",
        "#include <string.h>",
        "#include <stdlib.h>",
        "#ifndef _WIN32",
        "#include <unistd.h>",
        "#define EXISTS(p) (access((p), F_OK) == 0)",
        "#else",
        "#include <io.h>",
        "#define EXISTS(p) (_access((p), 0) == 0)",
        "#endif",
        "static int words(const char *s) { int n=0,in=0; for(; *s; s++){"
        " if(*s!=' '&&*s!='\\t'&&*s!='\\n'){ if(!in){ n++; in=1; } } else in=0; } return n; }",
        "int main(void) {",
        f'  const char *intent = "{_esc(door.intent)}";',
        f'  const char *pattern = "{_esc(door.pattern)}";',
        "  if (words(intent) > 17 || words(pattern) > 17) return 1;",
    ]
    for c in door.checks:
        if c.kind == "exists":
            lines.append(f'  if (!EXISTS("{_esc(c.args[0])}")) return 1;')
        elif c.kind == "words":
            var = "intent" if c.args[0] == "intent" else "pattern"
            lines.append(f"  if (words({var}) > {c.args[1]}) return 1;")
        elif c.kind == "run":
            lines.append(f'  if (system("{_esc(c.args[0])}") != 0) return 1;')
        elif c.kind == "contains":
            lines.append(
                f'  {{ FILE *f=fopen("{_esc(c.args[0])}","r"); if(!f) return 1;'
                " char b[65536]; size_t n=fread(b,1,sizeof b-1,f); b[n]=0; fclose(f);"
                f' if(!strstr(b,"{_esc(c.args[1])}")) return 1; }}'
            )
        elif c.kind == "eq":
            lines.append(
                f'  {{ FILE *f=fopen("{_esc(c.args[0])}","r"); if(!f) return 1;'
                " char b[65536]; size_t n=fread(b,1,sizeof b-1,f); b[n]=0; fclose(f);"
                f' if(strcmp(b,"{_esc(c.args[1])}")) return 1; }}'
            )
    lines += ['  puts("ok");', "  return 0;", "}"]
    return "\n".join(lines) + "\n"


def emit(door: Door, lang: str) -> str:
    if lang in {"python", "py"}:
        return emit_python(door)
    if lang in {"rust", "rs"}:
        return emit_rust(door)
    if lang in {"c"}:
        return emit_c(door)
    raise ValueError(f"unknown backend {lang}")
