"""Canonical meanings. A backend preserves a cell or refuses it."""

from __future__ import annotations

CANONICAL = {
    "words": "count whitespace-separated tokens of intent or pattern; pass iff count <= N",
    "exists": "path, confined to measure root, names an existing filesystem object",
    "contains": "confined path is a file whose text contains the given string",
    "eq": "confined path is a file whose exact text equals the given string",
    "run": "execute the command in a shell at the measure root; pass iff exit 0. requires allow_run",
    "use": "confined path is a YA|RA expression; parse and measure it under the same policy; pass iff the child outcome is ok",
    "measure all": "every check must pass; one fail contradicts the Intent; a refusal also contradicts",
    "measure any": "one passing check keeps the Intent unless a refusal occurred",
}

CONFORMANCE = {
    "python-measure": {
        "words": "preserved",
        "exists": "preserved",
        "contains": "preserved",
        "eq": "preserved",
        "run": "preserved",
        "use": "preserved",
        "measure all": "preserved",
        "measure any": "preserved",
    },
    "python-emit": {
        "words": "preserved",
        "exists": "preserved",
        "contains": "preserved",
        "eq": "preserved",
        "run": "preserved",
        "use": "preserved",
        "measure all": "preserved",
        "measure any": "preserved",
    },
    "c": {
        "words": "preserved",
        "exists": "preserved",
        "contains": "preserved",
        "eq": "preserved",
        "run": "preserved",
        "use": "unsupported",
        "measure all": "preserved",
        "measure any": "preserved",
    },
    "cxx": {
        "words": "preserved",
        "exists": "preserved",
        "contains": "preserved",
        "eq": "preserved",
        "run": "preserved",
        "use": "unsupported",
        "measure all": "preserved",
        "measure any": "preserved",
    },
    "rust": {
        "words": "preserved",
        "exists": "preserved",
        "contains": "preserved",
        "eq": "preserved",
        "run": "preserved",
        "use": "unsupported",
        "measure all": "preserved",
        "measure any": "unsupported",
    },
    "kernel": {
        "words": "preserved",
        "exists": "unsupported",
        "contains": "unsupported",
        "eq": "unsupported",
        "run": "unsupported",
        "use": "unsupported",
        "measure all": "preserved",
        "measure any": "unsupported",
    },
    "toe": {
        "words": "preserved",
        "exists": "preserved",
        "contains": "preserved",
        "eq": "preserved",
        "run": "preserved",
        "use": "unsupported",
        "measure all": "preserved",
        "measure any": "preserved",
    },
    "quantum": {
        "words": "observational",
        "exists": "observational",
        "contains": "observational",
        "eq": "observational",
        "run": "observational",
        "use": "observational",
        "measure all": "observational",
        "measure any": "observational",
    },
    "llm": {
        "words": "transport",
        "exists": "transport",
        "contains": "transport",
        "eq": "transport",
        "run": "transport",
        "use": "transport",
        "measure all": "transport",
        "measure any": "transport",
    },
}
